### ISSUE TITLE
Problems with contributing on Linux

### ISSUE THREAD

**Issue by jwr12135** [microsoft/vscode-hexeditor#373]
While working on the prevous pull requests, I encountered a number of problems while trying to compile with my Linux machine (it worked on my dual boot windows OS just fine, but I shouldn't have had to switch over just to test the code).

problem installing:

```sh
npm i # right after cloning
```

output:

```
npm ERR! code 1
npm ERR! path vscode-hexeditor/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
```

workaround:

```sh
npm i --ignore-scripts
node node_modules/esbuild/install.js
```

(I also tried clearing npm cache)

problem compiling:

```sh
npm run compile
```

output:

```
✘ [ERROR] [plugin linaria] The service was stopped
    
    node_modules/@linaria/esbuild/node_modules/esbuild/lib/main.js:1258:28:
      1258 │             return callback(new Error(error), null);
           ╵                             ^
    
    at vscode-hexeditor/node_modules/@linaria/esbuild/node_modules/esbuild/lib/main.js:1258:29
    at vscode-hexeditor/node_modules/@linaria/esbuild/node_modules/esbuild/lib/main.js:611:9
    at Socket.afterClose (vscode-hexeditor/node_modules/@linaria/esbuild/node_modules/esbuild/lib/main.js:589:7)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    
  This error came from the "onLoad" callback registered here:
    
    node_modules/@linaria/esbuild/lib/index.js:54:12:
      54 │       build.onLoad({
         ╵             ~~~~~~
    
    at setup (vscode-hexeditor/node_modules/@linaria/esbuild/lib/index.js:54:13)
    at handlePlugins (vscode-hexeditor/node_modules/esbuild/lib/main.js:814:23)
    at Object.buildOrServe (vscode-hexeditor/node_modules/esbuild/lib/main.js:1108:7)
    at vscode-hexeditor/node_modules/esbuild/lib/main.js:1961:17
    at new Promise (<anonymous>)
    at Object.build (vscode-hexeditor/node_modules/esbuild/lib/main.js:1960:14)
    at Object.build (vscode-hexeditor/node_modules/esbuild/lib/main.js:1814:51)
    at Object.<anonymous> (vscode-hexeditor/.esbuild.config.js:60:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

I couldn't figure out how to get it working after this, so I tried a different operating system (win 10) and got it working on that. Any help on this would be appreciated.

---

Possibly relevant information:

os: Ubuntu 20.04
node: v16.16.0
npm: v8.11.0

**Comment by lramos15** [comment]
Using your same exact setup: 
os: Ubuntu 20.04
node: v16.16.0
npm: v8.11.0

I was able to compile without issues or warnings.

@connor4312 Let me know if oyu have any ideas as well. Seems they're unable to download the native esbuild module.

**Comment by connor4312** [comment]
@jwr12135 when the install fails you should get an `npm-debug.log` or something along those lines (its path will be printed to your console.) Can you share that?

**Comment by jwr12135** [comment]
@connor4312, here is the log file: [2022-08-08T15_53_33_060Z-debug-0.log](https://github.com/microsoft/vscode-hexeditor/files/9283235/2022-08-08T15_53_33_060Z-debug-0.log).

**Comment by connor4312** [comment]
Hm, that's not particularly helpful. We can probably just try updating Linaria, we're on an old beta version.

**Comment by connor4312** [comment]
Updated Linaria
