### ISSUE TITLE
Unexpected token 'export' at @linaria\esbuild

### ISSUE THREAD

**Issue by wuanzhuan** [microsoft/vscode-hexeditor#413]
for compiling the main branch of hexeditor@1.9.10
yarn run v1.22.19
warning hexeditor@1.9.10: The engine "vscode" appears to be invalid.
$ tsc --noEmit && node .esbuild.config.js
X [ERROR] [plugin linaria] Unexpected token 'export' in
| C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\cockatiel\dist\esm\index.js
| C:\dev\github.com\microsoft\vscode-hexeditor\media\editor\dataDisplayContext.tsx

    media/editor/hexEdit.tsx:7:51:
      7 │ import { DataDisplayContext, DisplayContext } from "./dataDisplayContext";
        ╵                                                    ~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/@linaria/esbuild/dist/index.js:71:12:
      71 │       build.onLoad({ filter: /\.(js|jsx|ts|tsx)$/ }, async (args) => {
         ╵             ~~~~~~

    at setup (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\@linaria\esbuild\dist\index.js:71:13)
    at handlePlugins (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:1260:21)
    at buildOrServeImpl (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:951:5)
    at Object.buildOrServe (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:759:5)
    at C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:2096:17
    at new Promise (<anonymous>)
    at Object.build (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:2095:14)
    at Object.build (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:1942:51)
    at Object.<anonymous> (C:\dev\github.com\microsoft\vscode-hexeditor\.esbuild.config.js:70:3)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  This error came from the "onLoad" callback registered here:

    node_modules/@linaria/esbuild/dist/index.js:71:12:
      71 │       build.onLoad({ filter: /\.(js|jsx|ts|tsx)$/ }, async (args) => {
         ╵             ~~~~~~

    at setup (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\@linaria\esbuild\dist\index.js:71:13)
    at handlePlugins (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:1260:21)
    at buildOrServeImpl (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:951:5)
    at Object.buildOrServe (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:759:5)
    at C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:2096:17
    at new Promise (<anonymous>)
    at Object.build (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:2095:14)
    at Object.build (C:\dev\github.com\microsoft\vscode-hexeditor\node_modules\esbuild\lib\main.js:1942:51)
    at Object.<anonymous> (C:\dev\github.com\microsoft\vscode-hexeditor\.esbuild.config.js:70:3)

**Comment by connor4312** [comment]
This may be https://github.com/callstack/linaria/issues/1067 ish. I've also seen this, linaria doesn't built on Windows. Linaria is a pain, I want to just move off it.
