### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'DisplayContextSelection')

### ISSUE THREAD

**Issue by Hexa3333** [microsoft/vscode-hexeditor#547]
The hex editor is not rendering anything at all.
Reverting back to an older version fixed this issue so i assume there's a bug with the recent commit.
Here is the output i got from developer tools:
```
TypeError: Cannot read properties of undefined (reading 'DisplayContextSelection')
    at au (editor.js:10:82942)
    at new Tu (editor.js:10:118746)
    at editor.js:10:156986
    at Object.useMemo (editor.js:6:25844)
    at ne.useMemo (editor.js:1:6790)
    at n3 (editor.js:10:156981)
    at Ad (editor.js:6:19521)
    at Kv (editor.js:8:43972)
    at Wv (editor.js:8:39730)
    at tw (editor.js:8:39658)

Uncaught TypeError: Cannot read properties of undefined (reading 'DisplayContextSelection')
    at au (editor.js:10:82942)
    at new Tu (editor.js:10:118746)
    at editor.js:10:156986
    at Object.useMemo (editor.js:6:25844)
    at ne.useMemo (editor.js:1:6790)
    at n3 (editor.js:10:156981)
    at Ad (editor.js:6:19521)
    at Kv (editor.js:8:43972)
    at Wv (editor.js:8:39730)
    at tw (editor.js:8:39658)
```

**Comment by Antecer** [comment]
@connor4312 v1.11.0 can not show anything:
![Image](https://github.com/user-attachments/assets/f6e24d3f-4d5f-4654-b4ce-fbfd44af124e)
